Pequiven\SEIPBundle\Entity\Sip\Center\Observations:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        codigoCentro:
            expose: true
            groups: [codigoCentro]
        status:
            expose: true
            groups: [status]
        categoria:
            expose: true
            groups: [categoria]
        fecha:
            expose: true
            groups: [fecha]
        observations:
            expose: true
            groups: [observations]
        centro:
            expose: true
            groups: [api_list]
        municipio:
            expose: true
            groups: [api_list]
        parroquia:
            expose: true
            groups: [api_list]
        estado:
            expose: true
            groups: [api_list]