Pequiven\SEIPBundle\Entity\CEI\Company:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        description:
            expose: true
            groups: [api_list]