pequiven_consumer_planning_service_create:
    path: /{plantReport}/create
    defaults:
        _controller: pequiven.controller.consumer_planning_service:createAction
        _sylius:
            form: pequiven_seipbundle_dataload_service_consumerplanningservice
    methods: [GET|POST]
    
pequiven_consumer_planning_service_show:
    path: /{id}/show
    defaults:
        _controller: pequiven.controller.consumer_planning_service:showAction
    methods: [GET]
    
pequiven_consumer_planning_service_update:
    path: /{id}/update
    defaults:
        _controller: pequiven.controller.consumer_planning_service:updateAction
        _sylius:
            form: pequiven_seipbundle_dataload_service_consumerplanningservice
    methods: [GET|POST|PUT]
    
pequiven_consumer_planning_service_delete:
    path: /{id}/delete
    defaults:
        _controller: pequiven.controller.consumer_planning_service:deleteAction
    methods: [GET|DELETE]