pequiven_data_load:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/report_template.yml"
    prefix:   /report-template
    
pequiven_product_report:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/product_report.yml"
    prefix:   /product-report
    
pequiven_product_report_group:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/product_report_group.yml"
    prefix:   /product-report-group
    
pequiven_plant_report:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/plant_report.yml"
    prefix:   /plant-report
    
pequiven_data_load_product_planning:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/product_planning.yml"
    prefix:   /product-planning
    
pequiven_data_load_range:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/range.yml"
    prefix:   /range
    
pequiven_data_load_product_detail_daily_month:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/product_detail_daily_month.yml"
    prefix:   /product-detail-daily-month
    
pequiven_data_load_raw_material_consumption_planning:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/raw_material_consumption_planning.yml"
    prefix:   /raw-material-consumption-planning
    
pequiven_data_load_detail_raw_material_consumption:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/detail_raw_material_consumption.yml"
    prefix:   /detail-raw-material-consumption
    
pequiven_data_load_plant_stop_planning:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/plant_stop_planning.yml"
    prefix:   /plant-stop-planning
    
pequiven_data_load_consumer_planning_service:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/consumer_planning_service.yml"
    prefix:   /consumer-planning-service
    
pequiven_data_load_consumer_planning_gas_flow:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/consumer_planning_gas_flow.yml"
    prefix:   /consumer-planning-gasflow
    
pequiven_data_load_consumer_planning_service_factor:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/consumer_planning_service_factor.yml"
    prefix:   /consumer-planning-servicefactor
    
pequiven_data_load_inventory:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/inventory.yml"
    prefix:   /inventory
    
pequiven_data_load_unrealized_production:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/unrealized_production.yml"
    prefix:   /unrealized-production
    
pequiven_data_load_detail_consumer_planning_service:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/detail_consumer_planning_service.yml"
    prefix:   /detail-consumer-planning-service
    
pequiven_data_load_detail_consumer_planning_gas_flow:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/detail_consumer_planning_gas_flow.yml"
    prefix:   /detail-consumer-planning-gasflow
    
pequiven_data_load_detail_consumer_planning_service_factor:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/detail_consumer_planning_service_factor.yml"
    prefix:   /detail-consumer-planning-servicefactor
    
pequiven_data_load_dashboard:
    resource: "@PequivenSEIPBundle/Resources/config/routing/dataLoad/dashboard.yml"
    prefix:   /dashboard