## YAML Template.
pequiven_housesupply_order_charge:
    path: /orders/{type}/
    defaults:
        _controller: pequiven.controller.housesupply_order:chargeAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]

pequiven_housesupply_save_order:
    path: /orders/save
    defaults:
        _controller: pequiven.controller.housesupply_order:saveOrderAction
    