## YAML Template.
pequiven_housesupply_inventory_charge:
    path: /Charge
    defaults:
        _controller: pequiven.controller.housesupply_inventory_charge:chargeAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]