## YAML Template.
pequiven_housesupply_order_charge:
    path: /orders/create/
    defaults:
        _controller: pequiven.controller.housesupply_order:chargeAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_charge_add:
    path: /orders/create/add/
    defaults:
        _controller: pequiven.controller.housesupply_order:addAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_charge_remove:
    path: /orders/create/remove/
    defaults:
        _controller: pequiven.controller.housesupply_order:removeAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]

pequiven_housesupply_save_order:
    path: /orders/save
    defaults:
        _controller: pequiven.controller.housesupply_order:saveOrderAction
    