## YAML Template.
pequiven_housesupply_inventory_charge:
    path: /HouseSupply/Inventory/Charge
    defaults:
        _controller: PequivenSEIPBundle:HouseSupply/HouseSupplyInventory:chargeAction
    methods: [GET|POST]
    options:
        expose: true
