## YAML Template.
pequiven_housesupply_order_charge:
    path: /orders/create/{typemember}
    defaults:
        _controller: pequiven.controller.housesupply_order:chargeAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_register:
    path: /orders/register/
    defaults:
        _controller: pequiven.controller.housesupply_order:registerAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_charge_add:
    path: /orders/addItem/
    defaults:
        _controller: pequiven.controller.housesupply_order:addItemAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_charge_delete:
    path: /orders/deleteItem/{id}
    defaults:
        _controller: pequiven.controller.housesupply_order:deleteItemAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_charge_total:
    path: /orders/total/
    defaults:
        _controller: pequiven.controller.housesupply_order:totalAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]

pequiven_housesupply_save_order:
    path: /orders/save
    defaults:
        _controller: pequiven.controller.housesupply_order:saveOrderAction
    