pequiven_objetive_list:
    path: /{level}/list.{_format}
    defaults:
        _controller: pequiven.controller.objetive:listAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]
    
pequiven_objetive_update:
    path: /{id}/update.{_format}
    defaults:
        _controller: pequiven.controller.objetive:updateAction
        _format: html
        _sylius:
            form: pequiven_objetive_form
    requirements:
        _format: html|json
    methods: [GET|POST]
    
pequiven_objetive_approved:
    path: /{id}/approved.{_format}
    defaults:
        _controller: pequiven.controller.objetive:approvedAction
        _format: html
    requirements:
        _format: html
    methods: [POST]
    
pequiven_objetive_delete:
    path: /{id}/delete.{_format}
    defaults:
        _controller: pequiven.controller.objetive:deleteAction
        _format: json
    requirements:
        _format: json
    methods: [POST|DELETE]
    
#Select que devuelve las Gerencias de 1ra Línea para la visualización de objetivos a nivel Táctico
objetiveGerenciaFirstTactic:
    path: /objetive/objetiveGerenciaFirstTactic
    defaults:
        _controller: pequiven.controller.objetive:selectGerenciaFirstAction
        
#Select que devuelve las Gerencias de 2da Línea para la visualización de objetivos a nivel Operativo
objetiveGerenciaSecondOperative:
    path: /objetive/objetiveGerenciaSecondOperative
    defaults:
        _controller: pequiven.controller.objetive:selectGerenciaSecondListAction