parameters:
#    pequiven_sig.example.class: Pequiven\SIGBundle\Example

services:
#    pequiven_sig.example:
#        class: %pequiven_sig.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
