pequiven_delivery:
    resource: "@PequivenSEIPBundle/Resources/config/routing/delivery/report_template_delivery.yml"
    prefix:   /report-template-delivery
    
pequiven_product_group_delivery:
    resource: "@PequivenSEIPBundle/Resources/config/routing/delivery/product_group_delivery.yml"
    prefix:   /product-group-delivery
    
pequiven_product_report_delivery:
    resource: "@PequivenSEIPBundle/Resources/config/routing/delivery/product_report_delivery.yml"
    prefix:   /product-report-delivery