parameters:
    knp_menu.menu_builder.class: Pequiven\SEIPBundle\Menu\Template\Developer\BackendMenuBuilder
    knp_menu.voter.request.class: Pequiven\SEIPBundle\Menu\Template\Developer\RequestVoter
    knp_menu.renderer.twig.options:
        currentClass: current

services:
    app.menu_builder:
        class: "%knp_menu.menu_builder.class%"
        arguments: ["@knp_menu.factory", "@security.context", "@translator", "@service_container"]
        calls:
            - [ setContainer, [ @service_container ] ]

    app.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        # factory_service: app.menu_builder
        # factory_method: createSidebarMenu
        factory: ["@app.menu_builder", createSidebarMenu]
        arguments: ["@request", "@request_stack"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main }

    app.menu.voter.request:
        class: "%knp_menu.voter.request.class%"
        arguments: ["@service_container"]
        tags:
            - { name: knp_menu.voter }

    app.twig_string_loader:
        class:        "Twig_Loader_String"

    app.twig_string:
        class:        "%twig.class%"
        arguments:    [@app.twig_string_loader, %knp_menu.renderer.twig.options%]