Pequiven\MasterBundle\Entity\GerenciaGroup:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_list]
        userCreatedAt:
            expose: true
            groups: [api_details]
        userUpdatedAt:
            expose: true
            groups: [api_details]
        description:
            expose: true
            groups: [api_list]
        groupName:
            expose: true
            groups: [api_list]