Pequiven\MasterBundle\Entity\LineStrategic:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_details]
        userCreatedAt:
            expose: true
            groups: [api_details]
        userUpdatedAt:
            expose: true
            groups: [api_details]
        description:
            expose: true
            groups: [api_list]
        ref:
            expose: true
            groups: [api_list]
        politics:
            expose: true
            groups: [api_details]
        objetives:
            expose: true
            groups: [objetives]
        level:
            expose: true
            groups: [api_details]
        levelName:
            expose: true
            groups: [api_details]