Pequiven\MasterBundle\Entity\ArrangementProgram\CategoryArrangementProgram:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        description:
            expose: true
            groups: [api_list]
        active:
            expose: true
            groups: [api_list]