pequiven_seip_result_notify_arrangementprogram:
    path: /notify/arrangementprogram.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:indexAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_result_notify_indicator_strategic:
    path: /notify/indicator/strategic
    defaults: 
        _controller: pequiven.controller.indicatorstrategic:listAction
    
pequiven_seip_result_notify_indicator_tactic:
    path: /notify/indicator/tactic
    defaults: 
        _controller: pequiven.controller.indicatortactic:listAction
        
pequiven_seip_result_notify_indicator_operative:
    path: /notify/indicator/operative
    defaults: 
        _controller: pequiven.controller.indicatoroperative:listAction

pequiven_seip_result_visualize_by_gerencia:
    path: /visualize/by-gerencia.{_format}
    defaults:
        _controller: pequiven.controller.result:listResultAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]
    
pequiven_seip_result_visualize_gerencia:
    path: /visualize/gerencia/{level}/{id}.{_format}
    defaults:
        _controller: pequiven.controller.result:showMonitorAction
        _format: html
    requirements:
        _format: html|json|xml
        id: \d+
        level: 2|3
    methods: [GET]
    
pequiven_seip_result_export:
    path: /{level}/{id}/export
    defaults: { _controller: pequiven.controller.result:exportAction }
    requirements:
        id: "\d+"
    methods: [GET|POST]
    
pequiven_seip_result_export_from_chart:
    path: /{level}/{id}/export-from-chart
    defaults: { _controller: pequiven.controller.result:exportFromChartAction }
    requirements:
        id: "\d+"
    methods: [GET|POST]
    
pequiven_seip_result_visualize_objetives:
    path: /visualize/{_period}-objetives-{level}.{_format}
    defaults:
        _controller: pequiven.controller.result:indexObjetivesAction
        _format: html
    requirements:
        _format: html|json|xml
        _period: \d+
        level: 1|2|3
    methods: [GET]
    
pequiven_seip_result_visualize_indicators:
    path: /visualize/{_period}-indicators-{level}.{_format}
    defaults:
        _controller: pequiven.controller.result:indexIndicatorsAction
        _format: html
    requirements:
        _format: html|json|xml
        _period: \d+
        level: 1|2|3
    methods: [GET]
    
pequiven_seip_result_visualize_arrangement_programs:
    path: /visualize/{_period}-arrangement-programs.{_format}
    defaults:
        _controller: pequiven.controller.result:indexArrangementProgramsAction
        _format: html
    requirements:
        _format: html|json|xml
        _period: \d+
    methods: [GET]
    
pequiven_list_user_items:
    path: /listUserItems.{_format}
    defaults:
        _controller: pequiven.controller.result:userListItem
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_user_search_filter:
    path: /search.{_format}
    defaults:
        _controller: pequiven_seip.controller.user:searchFilterAction
        _format: json
    requirements:
        id: "\d+"
        _format: json
    methods: GET
    options:
        expose: true
        
pequiven_get_url_list_user:
    path: /.{_format}
    defaults:
        _controller: pequiven.controller.result:generateUrlFile
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    


pequiven_download_list_user_items:
    path: /.{_format}
    defaults:
        _controller: pequiven.controller.result:exportManagementUserListItem
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
