pequiven_value_indicator_get_form:
    path: /{idIndicator}/get-form.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:getFormAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
        
pequiven_value_indicator_calculate:
    path: /{idIndicator}/calculate.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:calculateAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true

pequiven_value_indicator_obtain_values:
    path: /{idIndicator}/obtain_values.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:obtainValuesAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
        
pequiven_value_indicator_add:
    path: /{idIndicator}/add.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:addAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
        
pequiven_value_indicator_show_detail:
    path: /{id}/show-detail.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:showDetailAction
        _format: html
    requirements:
        _format: html|json
    options:
        expose: true
        
pequiven_value_indicator_update_detail:
    path: /{id}/show-detail.{_format}/{slug}
    defaults:
        _controller: pequiven.controller.value_indicator:updateDetailAction
        _format: html
    requirements:
        _format: json
    options:
        expose: true