seip_api_result_useritems:
    path: /result/user-items.{_format}
    defaults: 
        _controller: PequivenSEIPBundle:Api/ResultApi:getUserItems
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    
seip_api_result_items_sai:
    path: /result/items-sai.{_format}
    defaults: 
        _controller: PequivenSEIPBundle:Api/ResultApi:getItemsSai
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]