create:
    path: /create
    defaults: {_controller: PequivenTrelloBundle:Trello:create}
    methods: [GET, POST]

approve:
    path: /update
    defaults: {_controller: PequivenTrelloBundle:Trello:update}
    methods: [POST]