Pequiven\IndicatorBundle\Entity\Indicator\ValueIndicator:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_list]
        createdBy:
            expose: true
            groups: [api_details]
        valueOfIndicator:
            expose: true
            groups: [api_list]
        formulaParameters:
            expose: true
            groups: [api_list]
        valueIndicatorDetail:
            expose: true
            gropups: [valueIndicatorDetail]