Pequiven\IndicatorBundle\Model\Indicator\ValueIndicator:
    exclusion_policy: ALL
    properties:
        formulaParameters:
            expose: true
            groups: [api_list]
        managementSystems:
            expose: true
            groups: [managementSystems]