goal:
    path: /
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:indexAction
    methods: [GET]
    
goal_create:
    path: /
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:createAction
    methods: [POST]
    
goal_new:
    path: /new
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:newAction
    methods: [GET]
    
goal_show:
    path: /{id}
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:showAction
    requirements:
        id: "\d+"
    methods: [GET]
    
goal_get_form:
    path: /get-form/{typeForm}
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:getFormAction
        typeForm: full
    requirements:
        typeForm: full|template
    methods: [GET]
    options:
        expose: true
        
goal_update:
    path: /{id}
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:updateAction
    methods: [PUT]
    
goal_delete:
    path: /{id}
    defaults: 
        _controller: pequiven_seip.controller.arrangementprogram_goal:deleteAction
    methods: [DELETE]
    
goal_movement:
    path: /mov.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:showAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
goal_movement_assign:
    path: /assign/{idGoal}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:assignAction
    methods: [GET|POST]
    options:
        expose: true
        
goal_movement_remove:
    path: /remove/{idGoal}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:removeAction
    methods: [GET|POST]
    options:
        expose: true
        
goal_movement_export:
    path: /export/{idGoal}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:exportAction
    methods: [GET|POST]
    options:
        expose: true
        
movement_delete:
    path: /delete/{idAffected}/{type}/{idMov}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:deleteAction
    methods: [GET|POST]
    options:
        expose: true
        
individual_value:
    path: /searchValue/{idGoal}/{idUser}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_goal:searchValuebyUserAction
    methods: [GET|POST]
    options:
        expose: true