pequiven_sig_route_monitoring:
    resource: "@PequivenSIGBundle/Resources/config/routing/monitoring.yml"
    
#ruta de Carga de Archivos generales de informe de evolución
pequiven_sig_evolution_load_file:
    path: /load-files-evolution/upload
    defaults:
        _controller: pequiven.controller.evolution:uploadAction
        _format: html    
    methods: [GET|POST]
pequiven_sig_evolution_download_file:
    path: /download-files-evolution/{typeObject}/{idObject}
    defaults:
        _controller: pequiven.controller.evolution:downloadAction
        _format: html    
    methods: [GET|POST]
#Ruta de informe de Evolucion de Objetivos
pequiven_sig_objetive_evolution_show:
    path: /objetive/{id}/evolution/{month}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:evolutionAction           
#Listado general de objetivos marcados con magementsystem
pequiven_objetives_list_sig:
    path: /sig/objetive/{level}.{_format}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:ObjetiveslistAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]
#Show de Objetivos pertenecientes a sistemas de calidad
pequiven_objetives_list_sig_show:
    path: /sig/objetive/show/{id}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:showAction
        _format: html    
#lista de objetivos con informes de evolución
pequiven_objetives_list_sig_evolution:
    path: /sig-evolution-{level}.{_format}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:ObjetiveslistEvolutionAction
        _format: html
    requirements:
        _format: html|json|xml        
        level: 1|2|3
    methods: [GET]
#listado de matriz de objetivos
pequiven_objetives_gerencia_list_sig:
    path: /adminMaster/list/sig.{_format}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:listAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Devuelve el paginador con la data de las gerencias de 1ra línea
pequiven_objetives_gerencia_list_:
    path: /adminMaster_list/gerenciaFirst
    defaults: 
        _controller: pequiven.controller.gerenciafirst:gerenciaFirstListAction
        _sylius:
            method: createPaginatorGerenciaFirst
#export matriz managementesystem
pequiven_sig_gerenciafirst_export:
    path: /adminMaster/list/{id}/export
    defaults: { _controller: pequiven.controller.managementsystem_sig_objetives:exportAction }
    requirements:
        id: "\d+"
    methods: [GET]
    options:
        expose: true

#Seguimiento a Carga de informes de evolución
pequiven_indicator_evolution_load:
    path: /indicator/sig/load
    defaults: 
        _controller: pequiven.controller.indicator_sig:loadAction
pequiven_indicator_evolution_load_url:
    path: /indicator/sig/load-url
    defaults: 
        _controller: pequiven.controller.indicator_sig:getUrlEvolutionAction
